mode     : selfcontained
framework: purus
github:
  user: zhenglei-gao
  repo: StatRMemo

# HIGHLIGHTER SETTINGS
highlighter: prettify
hitheme: twitter-bootstrap
prettify:
  linenums: true

# WIDGETS
widgets: [disqus, mathjax]
disqus:
  shortname: slidify



