title: Stat & R Memo
tagline: Environmental Safety and Statistics
logo: assets/img/Koala.jpg 
owner: Zhenglei Gao
author:
  email: zhenglei.gao@gmail.com
  github: zhenglei-gao
  firstname: Zhenglei
  lastname: Gao

social:
  github: zhenglei-gao
  stackoverflow: zhenglei

# Choose url: / for local development
url: http://zhenglei-gao.github.com/StatRMemo/
rawurl: https://raw.github.com/zhenglei-gao/StatRMemo/gh-pages/
# url: /
URL: http://github.com/zhenglei-gao/StatRMemo
navigation: 
  - {item: Home, href: index.html}
  - {item: About, href: about.html}
  - {item: Links, href: test.html}
