title: Environmental Safety and Statistics
tagline: Statistics, Regulatory Affairs, Ecotoxicology, Environmental Modelling
logo: assets/img/poirot.jpg 
owner: Zhenglei Gao
author:
  email: zhenglei.gao@gmail.com
  github: zhenglei-gao
  firstname: Zhenglei
  lastname: Gao

social:
  github: zhenglei-gao
  twitter: ramnath_vaidya

# Choose url: / for local development
url: http://zhenglei-gao.github.com/StatRMemo/
rawurl: https://raw.github.com/zhenglei-gao/StatRMemo/gh-pages/
# url: /
URL: http://github.com/zhenglei-gao/StatRMemo
navigation: 
  - {item: Home, href: index.html}
  - {item: About, href: about.html}
